// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQSNHXwwTpVBKLzPwns-PHbOY_RnIHPGA',
    appId: '1:223670475129:web:990fb667f4f67f195177a8',
    messagingSenderId: '223670475129',
    projectId: 'aai-e3733',
    authDomain: 'aai-e3733.firebaseapp.com',
    storageBucket: 'aai-e3733.firebasestorage.app',
    measurementId: 'G-6G50VN9E1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXodwFXcO_H5j-UIC-QhHeRJBw0NX3-8',
    appId: '1:223670475129:android:95fae970be54606a5177a8',
    messagingSenderId: '223670475129',
    projectId: 'aai-e3733',
    storageBucket: 'aai-e3733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcgD5GCe8xj-plNBAJxNCeiRghQbHdpSU',
    appId: '1:223670475129:ios:148c91d4bda52f6c5177a8',
    messagingSenderId: '223670475129',
    projectId: 'aai-e3733',
    storageBucket: 'aai-e3733.firebasestorage.app',
    iosBundleId: 'com.example.aai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQSNHXwwTpVBKLzPwns-PHbOY_RnIHPGA',
    appId: '1:223670475129:web:d27588f940836dbc5177a8',
    messagingSenderId: '223670475129',
    projectId: 'aai-e3733',
    authDomain: 'aai-e3733.firebaseapp.com',
    storageBucket: 'aai-e3733.firebasestorage.app',
    measurementId: 'G-XLMLJVPLY0',
  );
}
